voxel_grid:
  debug: False # Choose if to visualize the grid in every step.
  channels: 1
  compute_target: false
  params:
    type: scalable # Uniform or scalable. Fixed grid or adaptive.
    voxel_length_m: 0.1
    truncation_m: 0.8 # Safe against 0.5 horizontal, 0.5 vertical case.
    full_length_m: 10.0 # If fixed grid, the total size.
    max_weight: 10.0 # At the moment the C++ side can not be changed.

  local:
    width_m: 2.0 # Width of local tsdf blocks.
    height_upper_m: 0.3 # Upper Height of local tsdf blocks, 0.5 is when it reached the floor. (y points down)
    height_lower_m: -0.1 # Lower Height of local tsdf blocks, -0.1 is when it's 0.1 meters above robot.
    depth_m: 3.0 # Depth of local tsdf blocks.

  camera:
    width: 320
    height: 240
    fov: 60  # This is vertical fov in degrees.
    h_fov: 80  # This is horizontal fov (not precise, use only for rasterization for the fov.
    extrinsics: # Only support translation for now.
      x: 0.0
      y: 0.0
      z: 0.0
    max_depth_m: 50.0 # Depth camera can perceive up to 50 meters in depth.
    depth_truncation_m: 5.0  # Beyond which not considered
    ransac_dist_thresh_m: 0.01 # For depth filling

training:
  num_env: 1
  scene_id: [1]
  exp_name: default
  task: navigation
  timestamps: 500000 # 500k steps
  ep_len: 400
  log_interval: 1  # logging interval in terms of episodes not timesteps.

evaluation:
  scene_ids: [2, 3]
  task: navigation
  n_episodes: 2
  viz: False

agent:
  type: sac
  gamma: 0.995
  learning_rate: 0.0003
  buffer_size: 500000
  gradient_steps: 1
  policy: 'CnnPolicy'
  net_arch:
    - 128
    - 64
#  cnn_arch:
#    - 16
#    - 32
#  cnn_feature_dim: 128 # Size of features from 3D CNN output.
  batch_size: 32
  save_freq: 5000
  verbose: 1

rewards:
#  - type: by_forward_movement
#    weight: 0.1
  - type: by_collision
    weight: -1
  - type: by_decay
    weight: -0.01
  - type: by_target_pursuit
    weight: 0.1
    angular_weight: 0.02

# Need another reward that encourages target pursuit, this can replace forward movement. TODO(jd)
#  - type: by_pursuit
#    weight: 0.1

  # Give reward if new voxels are discovered.
#  - type: by_exploration
#    weight: 0.8
  # Give reward if target is observed.
#  - type: by_observation
#    weight: 1.2


#  - type: by_distance_traveled
#    weight: 0.005
